export const HomeActionTypes = {
  SET_PRODUCTS: "SET_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  DISPLAY_IMG: "DISPLAY_IMG",
  ADD_CART_PRODUCT: "ADD_CART_PRODUCT",
  REMOVE_CART_PRODUCT: "REMOVE_CART_PRODUCT",
  REMOVE_ONE_CART : "REMOVE_ONE_CART",
  ADD_WISHLIST_PRODUCT: "ADD_WISHLIST_PRODUCT",
  REMOVE_WISHLIST_PRODUCT: "REMOVE_WISHLIST_PRODUCT",
  FILTERED_PRODUCT : "FILTERED_PRODUCT",

};
